version: '3'
services:
  beat:
    image: docker.elastic.co/apm/apm-server:7.1.1
    ports:
      - "8200:8200"
      - "8201:8200"
    environment:
      - apm-server.host=0.0.0.0
    volumes:
      - ./apm-server-kafka.yml:/usr/share/apm-server/apm-server.yml
    depends_on:
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.80.175
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "payments:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
