version: '3'
services:
  beat:
    image: docker.elastic.co/apm/apm-server:7.1.1
    ports:
      - "8200:8200"
      - "8201:8200"
    environment:
      - apm-server.host=0.0.0.0
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - apm
    depends_on:
      - elasticsearch
      - kibana
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    # network_mode: "service:elasticsearch"
    # volumes:
    #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ELASTIC_PASSWORD=password
    networks:
      - apm
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    # volumes:
    #     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - apm
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=password
    depends_on:
      - elasticsearch

networks:
  apm:
    driver: bridge
