version: '3'
services:
  beat:
    image: docker.elastic.co/apm/apm-server:7.1.1
    ports:
      - "8300:8300"
      - "8201:8300"
    environment:
      - apm-server.host=0.0.0.0
    volumes:
      - ./apm-server-logstash.yml:/usr/share/apm-server/apm-server.yml
    depends_on:
      - logstash
  logstash:
    image: logstash:7.1.1
    ports:
      - "5044:5044"
    links:
      - kafka
    volumes:
      - ./:/config-dir
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    command: logstash -f /config-dir/logstash.conf
    depends_on:
      - kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.22
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "payments:1:1,\
                           rw_payments_manager:1:1,\
                           rw_payment_events:1:1,\
                           rw_boleto_events:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
